### ISSUE TITLE
Error when running `npm run build`

### ISSUE THREAD

**Issue by remjx** [necolas/icon-builder-example#2]
This looks awesome! However I'm getting this error: 

```
$ npm run build

> @acme/icons@1.0.1 build C:\Users\markj\workspace\icon-builder
> node scripts/build.js

Optimizing icon: "alerts"
Optimizing icon: "camera"
Optimizing icon: "circle"
{ TypeError: unknown: Property value expected type of string but got null
    at Object.validate (C:\Users\markj\workspace\icon-builder\node_modules\babel-types\lib\definitions\index.js:161:13)
    at validate (C:\Users\markj\workspace\icon-builder\node_modules\babel-types\lib\index.js:505:9)
    at Object.builder (C:\Users\markj\workspace\icon-builder\node_modules\babel-types\lib\index.js:466:7)
    at PluginPass.JSXOpeningElement (C:\Users\markj\workspace\icon-builder\node_modules\babel-plugin-transform-react-jsx-source\lib\index.js:35:68)
    at newFn (C:\Users\markj\workspace\icon-builder\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\markj\workspace\icon-builder\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\markj\workspace\icon-builder\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\markj\workspace\icon-builder\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\markj\workspace\icon-builder\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\markj\workspace\icon-builder\node_modules\babel-traverse\lib\context.js:108:19) _babel: true }
```

Any ideas? Thanks!

**Comment by paragwaghela-bh** [comment]
I am also facing same error !!
